logging:
  level:
    ROOT: INFO
    com.microservices.demo: DEBUG

spring:
  application:
    name: elastic-query-service
  profiles:
    active: elastic_query
  config:
    import: 'configserver:'
  cloud:
    config:
      name: elastic-query-service,config-client
      username: user
      password: password

log:
  appName: elastic-query-service