version: '3.7'
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - '9091:9091'
    command: start-dev
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_HTTP_PORT=9091"
      - "KC_HOSTNAME=localhost"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/keycloak"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=keycloak"


#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: keycloak
#    ports:
#      - "5432:5432"
#    restart: always

#version: '3.7'
#services:
#  keycloak-authorization-server:
#    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
#    hostname: keycloak-server
#    ports:
#      - "9091:9091"
#    command: start-dev
#    environment:
#      - "KEYCLOAK_USER=admin"
#      - "KEYCLOAK_PASSWORD=admin"
#      - "JAVA_OPTS=-Djboss.http.port=9091"
#      - "DB_VENDOR=POSTGRES"
#      - "DB_ADDR=host.docker.internal"
#      - "DB_DATABASE=keycloak"
#      - "DB_USER=keycloak"
#      - "DB_SCHEMA=keycloak"
#      - "DB_PASSWORD=keycloak"