version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - app
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql


networks:
  app:
    driver: bridge

volumes:
  mysql_data: