twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservice
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello
  enable-mock-tweets: true
  mock-min-tweet-lenght: 5
  mock-sleep-ms: 10000
