spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: user
      password: password

log:
  app-name: kafka-to-elastic-service

#spring:
#  application:
#    name: kafka-to-elastic-service
#  profiles:
#    active: kafka_to_elastic
#  config:
#    import: 'configserver:'
#  cloud:
#    config:
#      name: kafka-to-elastic-service,config-client
##      uri: http://localhost:8888
#      username: user
#      password: password


#log:
#  app-name: kafka-to-elastic-services

logging:
  level:
    ROOT: INFO

#spring:
#  application:
#    name: kafka-to-elastic-service
#  profiles:
#    active: kafka_to_elastic
#    config:
#      import: 'configserver:'
#  cloud:
#    config:
#      name: kafka-to-elastic-service,config-client
##      uri: http://localhost:8888
#      username: user
#      password: password